wandb: Currently logged in as: stevenzhou0816100. Use `wandb login --relogin` to force relogin
The following values were not passed to `accelerate launch` and had defaults used instead:
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/weird_training_largeplussmall.py", line 1088, in <module>
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/weird_training_largeplussmall.py", line 1088, in <module>
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/weird_training_largeplussmall.py", line 1088, in <module>
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/weird_training_largeplussmall.py", line 1088, in <module>
        large_model = LlamaWeirdLargeFullCoverage.from_pretrained(args.finetune_checkpoint) Traceback (most recent call last):
large_model = LlamaWeirdLargeFullCoverage.from_pretrained(args.finetune_checkpoint) 
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/weird_training_largeplussmall.py", line 1088, in <module>

  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/modeling_utils.py", line 2792, in from_pretrained
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/modeling_utils.py", line 2792, in from_pretrained
    large_model = LlamaWeirdLargeFullCoverage.from_pretrained(args.finetune_checkpoint) 
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/modeling_utils.py", line 2792, in from_pretrained
    large_model = LlamaWeirdLargeFullCoverage.from_pretrained(args.finetune_checkpoint) 
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/modeling_utils.py", line 2792, in from_pretrained
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/weird_training_largeplussmall.py", line 1088, in <module>
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/weird_training_largeplussmall.py", line 1088, in <module>
    large_model = LlamaWeirdLargeFullCoverage.from_pretrained(args.finetune_checkpoint) 
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/modeling_utils.py", line 2792, in from_pretrained
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/weird_training_largeplussmall.py", line 1088, in <module>
        large_model = LlamaWeirdLargeFullCoverage.from_pretrained(args.finetune_checkpoint) large_model = LlamaWeirdLargeFullCoverage.from_pretrained(args.finetune_checkpoint) 

  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/modeling_utils.py", line 2792, in from_pretrained
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/modeling_utils.py", line 2792, in from_pretrained
    large_model = LlamaWeirdLargeFullCoverage.from_pretrained(args.finetune_checkpoint) 
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/modeling_utils.py", line 2792, in from_pretrained
                config, model_kwargs = cls.config_class.from_pretrained(config, model_kwargs = cls.config_class.from_pretrained(config, model_kwargs = cls.config_class.from_pretrained(config, model_kwargs = cls.config_class.from_pretrained(



  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 594, in from_pretrained
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 594, in from_pretrained
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 594, in from_pretrained
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 594, in from_pretrained
            config, model_kwargs = cls.config_class.from_pretrained(config, model_kwargs = cls.config_class.from_pretrained(config, model_kwargs = cls.config_class.from_pretrained(


  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 594, in from_pretrained
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 594, in from_pretrained
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 594, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 594, in from_pretrained
                config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)            config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)

config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)

  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 623, in get_config_dict
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 623, in get_config_dict



  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 623, in get_config_dict
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 623, in get_config_dict
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 623, in get_config_dict
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 623, in get_config_dict
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 623, in get_config_dict
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 623, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 678, in _get_config_dict
            config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)            config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)

  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 678, in _get_config_dict
    


  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 678, in _get_config_dict
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 678, in _get_config_dict
resolved_config_file = cached_file(  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 678, in _get_config_dict
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 678, in _get_config_dict
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 678, in _get_config_dict

  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/utils/hub.py", line 360, in cached_file
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/configuration_utils.py", line 678, in _get_config_dict
        resolved_config_file = cached_file(resolved_config_file = cached_file(

  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/utils/hub.py", line 360, in cached_file
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/utils/hub.py", line 360, in cached_file
            resolved_config_file = cached_file(    resolved_config_file = cached_file(resolved_config_file = cached_file(
resolved_config_file = cached_file(

  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/utils/hub.py", line 360, in cached_file

  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/utils/hub.py", line 360, in cached_file
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/utils/hub.py", line 360, in cached_file
  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/utils/hub.py", line 360, in cached_file
                raise EnvironmentError(    raise EnvironmentError(    raise EnvironmentError(raise EnvironmentError(
raise EnvironmentError(
raise EnvironmentError(
    
OSError
OSError
OSErrorresolved_config_file = cached_file(OSError: OSError: OSError: 
: /fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902//main' for available files.: /fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902//main' for available files.: /fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902//main' for available files.  File "/opt/hpcaas/.mounts/fs-03efe25c053395d1f/beidic/yang/transformersprofiling/src/transformers/utils/hub.py", line 360, in cached_file
/fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902//main' for available files.
    /fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902//main' for available files.
/fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902//main' for available files.

raise EnvironmentError(


OSError: /fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902//main' for available files.
    raise EnvironmentError(
OSError: /fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//fsx-storygen/beidic/yang/model_checkpoints/tinyllama_setting3_7_d2b204b_087902//main' for available files.
[2024-04-24 22:44:07,906] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 545767) of binary: /data/home/beidic/anaconda3/envs/yangllm2/bin/python3.9
Traceback (most recent call last):
  File "/data/home/beidic/anaconda3/envs/yangllm2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/home/beidic/anaconda3/envs/yangllm2/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/data/home/beidic/anaconda3/envs/yangllm2/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/data/home/beidic/anaconda3/envs/yangllm2/lib/python3.9/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/data/home/beidic/anaconda3/envs/yangllm2/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/home/beidic/anaconda3/envs/yangllm2/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/home/beidic/anaconda3/envs/yangllm2/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
weird_training_largeplussmall.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-04-24_22:44:07
  host      : a100-st-p4de24xlarge-1030.fair-a100.hpcaas
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 545768)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-04-24_22:44:07
  host      : a100-st-p4de24xlarge-1030.fair-a100.hpcaas
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 545769)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-04-24_22:44:07
  host      : a100-st-p4de24xlarge-1030.fair-a100.hpcaas
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 545770)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-04-24_22:44:07
  host      : a100-st-p4de24xlarge-1030.fair-a100.hpcaas
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 545771)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-04-24_22:44:07
  host      : a100-st-p4de24xlarge-1030.fair-a100.hpcaas
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 545772)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-04-24_22:44:07
  host      : a100-st-p4de24xlarge-1030.fair-a100.hpcaas
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 545773)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-04-24_22:44:07
  host      : a100-st-p4de24xlarge-1030.fair-a100.hpcaas
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 545774)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-24_22:44:07
  host      : a100-st-p4de24xlarge-1030.fair-a100.hpcaas
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 545767)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
